# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'AppIOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AppIOS

  pod 'Firebase/Core'
  pod 'Firebase/Firestore'

end
