name: AppIOS
options:
  minimumXcodeGenVersion: 2.2.0
targets:
  AppIOS:
    platform: iOS
    type: application
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: by.cedon.skabs.multiplatform
    sources:
      - AppIOS
    dependencies:
      - framework: CommonClient.framework
